import type { PolarisPluginManifest } from './types'
import { pluginRegistry } from './registry'
import { todoPluginManifest } from '@/plugins/todo/manifest'
import { longGoalPluginManifest } from '@/plugins/longGoal/manifest'

const corePluginManifest: PolarisPluginManifest = {
  id: 'polaris.core',
  name: 'Polaris Core',
  version: '0.1.0',
  description: 'Polaris 内置基础面板入口。',
  builtin: true,
  enabledByDefault: true,
  contributes: {
    views: [
      {
        id: 'chat.panel',
        area: 'activityBar',
        moduleId: 'chat',
        icon: 'Bot',
        labelKey: 'labels.aiAssistant',
        labelDefault: 'AI Assistant',
        order: 5,
        allowedSlots: ['right', 'center'],
        defaultSlot: 'right',
        preferredSize: 400,
        bareRender: true,
      },
      {
        id: 'files.panel',
        area: 'activityBar',
        moduleId: 'files',
        icon: 'Files',
        labelKey: 'labels.fileExplorer',
        labelDefault: 'File Explorer',
        order: 10,
        allowedSlots: ['left', 'right', 'bottom'],
        defaultSlot: 'left',
        preferredSize: 280,
      },
      {
        id: 'git.panel',
        area: 'activityBar',
        moduleId: 'git',
        icon: 'GitPullRequest',
        labelKey: 'labels.gitPanel',
        labelDefault: 'Git',
        order: 20,
        allowedSlots: ['left', 'right', 'bottom'],
        defaultSlot: 'left',
        preferredSize: 280,
      },
      {
        id: 'translate.panel',
        area: 'activityBar',
        moduleId: 'translate',
        icon: 'Languages',
        labelKey: 'labels.translatePanel',
        labelDefault: 'Translate',
        order: 40,
        allowedSlots: ['left', 'right'],
        defaultSlot: 'left',
        preferredSize: 320,
      },
      {
        id: 'scheduler.panel',
        area: 'activityBar',
        moduleId: 'scheduler',
        icon: 'Clock',
        labelKey: 'labels.schedulerPanel',
        labelDefault: 'Scheduler',
        order: 50,
        allowedSlots: ['left', 'right', 'bottom'],
        defaultSlot: 'left',
        preferredSize: 360,
      },
      {
        id: 'requirement.panel',
        area: 'activityBar',
        moduleId: 'requirement',
        icon: 'ClipboardList',
        labelKey: 'labels.requirementPanel',
        labelDefault: 'Requirements',
        order: 60,
        allowedSlots: ['left', 'right', 'bottom'],
        defaultSlot: 'left',
        preferredSize: 320,
      },
      {
        id: 'terminal.panel',
        area: 'activityBar',
        moduleId: 'terminal',
        icon: 'Terminal',
        labelKey: 'labels.terminalPanel',
        labelDefault: 'Terminal',
        order: 70,
        allowedSlots: ['left', 'right', 'bottom'],
        defaultSlot: 'bottom',
        preferredSize: 220,
        keepAlive: true,
      },
      {
        id: 'developer.panel',
        area: 'activityBar',
        moduleId: 'developer',
        icon: 'Code2',
        labelKey: 'labels.developerPanel',
        labelDefault: 'Developer',
        order: 80,
        allowedSlots: ['left', 'right', 'bottom'],
        defaultSlot: 'left',
        preferredSize: 360,
      },
      {
        id: 'integration.panel',
        area: 'activityBar',
        moduleId: 'integration',
        icon: 'Bot',
        labelKey: 'labels.integrationPanel',
        labelDefault: 'Integration',
        order: 90,
        allowedSlots: ['left', 'right'],
        defaultSlot: 'left',
        preferredSize: 320,
      },
      {
        id: 'problems.panel',
        area: 'activityBar',
        moduleId: 'problems',
        icon: 'AlertCircle',
        labelKey: 'labels.problemsPanel',
        labelDefault: 'Problems',
        order: 110,
        badge: 'problems',
        allowedSlots: ['left', 'right', 'bottom'],
        defaultSlot: 'bottom',
        preferredSize: 200,
      },
    ],
  },
  permissions: {},
}

export function registerBuiltinPlugins(): void {
  pluginRegistry.register(corePluginManifest)
  pluginRegistry.register(todoPluginManifest)
  pluginRegistry.register(longGoalPluginManifest)
}

registerBuiltinPlugins()
