import {
  Activity,
  AlertCircle,
  BookOpen,
  Bot,
  CheckSquare,
  ClipboardList,
  Clock,
  Code2,
  Files,
  Film,
  GitPullRequest,
  Globe2,
  Languages,
  Target,
  Terminal,
  Users,
  type LucideIcon,
} from 'lucide-react'
import type { PluginIconId } from './types'

export const pluginIconMap: Record<PluginIconId, LucideIcon> = {
  Activity,
  AlertCircle,
  BookOpen,
  Bot,
  CheckSquare,
  ClipboardList,
  Clock,
  Code2,
  Files,
  Film,
  Globe2,
  GitPullRequest,
  Languages,
  Terminal,
  Target,
  Users,
}
