//! Requirement commands for unified requirement management
//!
//! Provides Tauri commands for frontend to interact with the unified requirement repository.

use std::collections::BTreeMap;
use std::path::PathBuf;

#[cfg(feature = "tauri-app")]
use tauri::{AppHandle, Manager};

use crate::error::Result;
use crate::models::requirement::{
    QueryScope, RequirementCreateParams, RequirementExecuteConfig, RequirementItem,
    RequirementPriority, RequirementSource, RequirementStatus, RequirementUpdateParams,
};
use crate::services::unified_requirement_repository::UnifiedRequirementRepository;

// ============================================================================
// List requirements
// ============================================================================

#[derive(Debug, Clone, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ListRequirementsParams {
    /// Query scope: "workspace" or "all"
    #[serde(default)]
    pub scope: String,
    /// Workspace path (optional)
    pub workspace_path: Option<String>,
    /// Status filter (optional)
    pub status: Option<String>,
    /// Priority filter (optional)
    pub priority: Option<String>,
    /// Limit (optional)
    pub limit: Option<u32>,
}

#[cfg(feature = "tauri-app")]
#[tauri::command]
pub async fn list_requirements(
    params: ListRequirementsParams,
    app: AppHandle,
) -> Result<Vec<RequirementItem>> {
    let config_dir = app
        .path()
        .app_config_dir()
        .map_err(|e| crate::error::AppError::ProcessError(format!("获取配置目录失败: {}", e)))?;

    let workspace_path = params
        .workspace_path
        .filter(|p| !p.trim().is_empty())
        .map(PathBuf::from);

    let repository = UnifiedRequirementRepository::new(config_dir, workspace_path);
    repository.register_workspace().ok();

    let scope = match params.scope.as_str() {
        "all" => QueryScope::All,
        _ => QueryScope::Workspace,
    };

    let mut requirements = repository.list_requirements(scope)?;

    // Apply filters
    if let Some(status) = params.status {
        if let Ok(status) = parse_status(&status) {
            requirements.retain(|r| r.status == status);
        }
    }

    if let Some(priority) = params.priority {
        if let Ok(priority) = parse_priority(&priority) {
            requirements.retain(|r| r.priority == priority);
        }
    }

    if let Some(limit) = params.limit {
        requirements.truncate(limit as usize);
    }

    Ok(requirements)
}

// ============================================================================
// Create requirement
// ============================================================================

#[derive(Debug, Clone, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CreateRequirementParams {
    /// Requirement title
    pub title: String,
    /// Requirement description
    pub description: String,
    /// Priority
    #[serde(default)]
    pub priority: Option<String>,
    /// Tags
    pub tags: Option<Vec<String>>,
    /// Has prototype
    pub has_prototype: Option<bool>,
    /// Generated by
    pub generated_by: Option<String>,
    /// Generator task ID
    pub generator_task_id: Option<String>,
    /// Workspace path
    pub workspace_path: Option<String>,
}

#[cfg(feature = "tauri-app")]
#[tauri::command]
pub async fn create_requirement(
    params: CreateRequirementParams,
    app: AppHandle,
) -> Result<RequirementItem> {
    let config_dir = app
        .path()
        .app_config_dir()
        .map_err(|e| crate::error::AppError::ProcessError(format!("获取配置目录失败: {}", e)))?;

    let workspace_path = params
        .workspace_path
        .filter(|p| !p.trim().is_empty())
        .map(PathBuf::from);

    let repository = UnifiedRequirementRepository::new(config_dir.clone(), workspace_path.clone());

    if workspace_path.is_some() {
        repository.register_workspace().ok();
    }

    let priority = params
        .priority
        .and_then(|p| parse_priority(&p).ok())
        .unwrap_or_default();

    let generated_by = params
        .generated_by
        .and_then(|s| parse_source(&s).ok())
        .unwrap_or_default();

    let create_params = RequirementCreateParams {
        title: params.title,
        description: params.description,
        priority: Some(priority),
        tags: params.tags,
        has_prototype: params.has_prototype,
        generated_by: Some(generated_by),
        generator_task_id: params.generator_task_id,
    };

    repository.create_requirement(create_params)
}

// ============================================================================
// Update requirement
// ============================================================================

#[derive(Debug, Clone, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UpdateRequirementParams {
    /// Requirement ID
    pub id: String,
    /// Title
    pub title: Option<String>,
    /// Description
    pub description: Option<String>,
    /// Status
    pub status: Option<String>,
    /// Priority
    pub priority: Option<String>,
    /// Tags
    pub tags: Option<Vec<String>>,
    /// Prototype path
    pub prototype_path: Option<String>,
    /// Has prototype
    pub has_prototype: Option<bool>,
    /// Review note
    pub review_note: Option<String>,
    /// Execute log
    pub execute_log: Option<String>,
    /// Execute error
    pub execute_error: Option<String>,
    /// Generated by
    pub generated_by: Option<String>,
    /// Session ID
    pub session_id: Option<String>,
    /// Execute config
    pub execute_config: Option<ExecuteConfigParam>,
    /// Workspace path
    pub workspace_path: Option<String>,
}

#[derive(Debug, Clone, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExecuteConfigParam {
    pub scheduled_at: Option<i64>,
    pub engine_id: Option<String>,
    pub work_dir: Option<String>,
}

#[cfg(feature = "tauri-app")]
#[tauri::command]
pub async fn update_requirement(
    params: UpdateRequirementParams,
    app: AppHandle,
) -> Result<RequirementItem> {
    let config_dir = app
        .path()
        .app_config_dir()
        .map_err(|e| crate::error::AppError::ProcessError(format!("获取配置目录失败: {}", e)))?;

    let workspace_path = params
        .workspace_path
        .filter(|p| !p.trim().is_empty())
        .map(PathBuf::from);

    let repository = UnifiedRequirementRepository::new(config_dir, workspace_path);

    let execute_config = params.execute_config.map(|ec| RequirementExecuteConfig {
        scheduled_at: ec.scheduled_at,
        engine_id: ec.engine_id,
        work_dir: ec.work_dir,
    });

    let update_params = RequirementUpdateParams {
        title: params.title,
        description: params.description,
        status: params.status.and_then(|s| parse_status(&s).ok()),
        priority: params.priority.and_then(|p| parse_priority(&p).ok()),
        tags: params.tags,
        prototype_path: params.prototype_path,
        has_prototype: params.has_prototype,
        review_note: params.review_note,
        execute_config,
        execute_log: params.execute_log,
        execute_error: params.execute_error,
        generated_by: params.generated_by.and_then(|s| parse_source(&s).ok()),
        session_id: params.session_id,
    };

    repository.update_requirement(&params.id, update_params)
}

// ============================================================================
// Delete requirement
// ============================================================================

#[derive(Debug, Clone, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeleteRequirementParams {
    /// Requirement ID
    pub id: String,
    /// Workspace path
    pub workspace_path: Option<String>,
}

#[cfg(feature = "tauri-app")]
#[tauri::command]
pub async fn delete_requirement(
    params: DeleteRequirementParams,
    app: AppHandle,
) -> Result<RequirementItem> {
    let config_dir = app
        .path()
        .app_config_dir()
        .map_err(|e| crate::error::AppError::ProcessError(format!("获取配置目录失败: {}", e)))?;

    let workspace_path = params
        .workspace_path
        .filter(|p| !p.trim().is_empty())
        .map(PathBuf::from);

    let repository = UnifiedRequirementRepository::new(config_dir, workspace_path);

    repository.delete_requirement(&params.id)
}

// ============================================================================
// Save / Read prototype
// ============================================================================

#[derive(Debug, Clone, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SavePrototypeParams {
    pub id: String,
    pub html: String,
    pub workspace_path: Option<String>,
}

#[cfg(feature = "tauri-app")]
#[tauri::command]
pub async fn save_requirement_prototype(
    params: SavePrototypeParams,
    app: AppHandle,
) -> Result<String> {
    let config_dir = app
        .path()
        .app_config_dir()
        .map_err(|e| crate::error::AppError::ProcessError(format!("获取配置目录失败: {}", e)))?;

    let workspace_path = params
        .workspace_path
        .filter(|p| !p.trim().is_empty())
        .map(PathBuf::from);

    let repository = UnifiedRequirementRepository::new(config_dir, workspace_path);

    repository.save_prototype(&params.id, &params.html)
}

#[derive(Debug, Clone, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ReadPrototypeParams {
    pub prototype_path: String,
    pub workspace_path: Option<String>,
}

#[cfg(feature = "tauri-app")]
#[tauri::command]
pub async fn read_requirement_prototype(
    params: ReadPrototypeParams,
    app: AppHandle,
) -> Result<String> {
    let config_dir = app
        .path()
        .app_config_dir()
        .map_err(|e| crate::error::AppError::ProcessError(format!("获取配置目录失败: {}", e)))?;

    let workspace_path = params
        .workspace_path
        .filter(|p| !p.trim().is_empty())
        .map(PathBuf::from);

    let repository = UnifiedRequirementRepository::new(config_dir, workspace_path);

    repository.read_prototype(&params.prototype_path)
}

// ============================================================================
// Get workspace breakdown
// ============================================================================

#[derive(Debug, Clone, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GetBreakdownParams {
    pub workspace_path: Option<String>,
}

#[cfg(feature = "tauri-app")]
#[tauri::command]
pub async fn get_requirement_workspace_breakdown(
    params: GetBreakdownParams,
    app: AppHandle,
) -> Result<BTreeMap<String, usize>> {
    let config_dir = app
        .path()
        .app_config_dir()
        .map_err(|e| crate::error::AppError::ProcessError(format!("获取配置目录失败: {}", e)))?;

    let workspace_path = params
        .workspace_path
        .filter(|p| !p.trim().is_empty())
        .map(PathBuf::from);

    let repository = UnifiedRequirementRepository::new(config_dir, workspace_path);

    repository.get_workspace_breakdown()
}

// ============================================================================
// Helpers
// ============================================================================

fn parse_status(value: &str) -> Result<RequirementStatus> {
    match value {
        "draft" => Ok(RequirementStatus::Draft),
        "pending" => Ok(RequirementStatus::Pending),
        "approved" => Ok(RequirementStatus::Approved),
        "rejected" => Ok(RequirementStatus::Rejected),
        "executing" => Ok(RequirementStatus::Executing),
        "completed" => Ok(RequirementStatus::Completed),
        "failed" => Ok(RequirementStatus::Failed),
        _ => Err(crate::error::AppError::ValidationError(format!(
            "无效状态: {}",
            value
        ))),
    }
}

fn parse_priority(value: &str) -> Result<RequirementPriority> {
    match value {
        "low" => Ok(RequirementPriority::Low),
        "normal" => Ok(RequirementPriority::Normal),
        "high" => Ok(RequirementPriority::High),
        "urgent" => Ok(RequirementPriority::Urgent),
        _ => Err(crate::error::AppError::ValidationError(format!(
            "无效优先级: {}",
            value
        ))),
    }
}

fn parse_source(value: &str) -> Result<RequirementSource> {
    match value {
        "ai" => Ok(RequirementSource::Ai),
        "user" => Ok(RequirementSource::User),
        _ => Err(crate::error::AppError::ValidationError(format!(
            "无效来源: {}",
            value
        ))),
    }
}
