import { useState, useCallback } from 'react'

interface HostEntry {
  ip: string
  hostname: string
  enabled: boolean
  comment?: string
}

const MOCK_HOSTS: HostEntry[] = [
  { ip: '127.0.0.1', hostname: 'localhost', enabled: true },
  { ip: '::1', hostname: 'localhost', enabled: true },
  { ip: '192.168.1.100', hostname: 'dev-server.local', enabled: true, comment: '开发服务器' },
  { ip: '10.0.0.50', hostname: 'api.local', enabled: true, comment: 'API 服务' },
  { ip: '172.16.0.10', hostname: 'db.local', enabled: false, comment: '数据库 (已禁用)' },
  { ip: '0.0.0.0', hostname: 'example.com', enabled: false, comment: '屏蔽示例域名' },
]

export default function HostEditorPanel({ pluginId }: { pluginId: string; onSendToChat?: (msg: string) => void }) {
  const [hosts, setHosts] = useState<HostEntry[]>(MOCK_HOSTS)
  const [search, setSearch] = useState('')
  const [newIp, setNewIp] = useState('')
  const [newHostname, setNewHostname] = useState('')
  const [newComment, setNewComment] = useState('')
  const [copied, setCopied] = useState(false)

  const filtered = hosts.filter(
    (h) =>
      h.ip.includes(search.toLowerCase()) ||
      h.hostname.toLowerCase().includes(search.toLowerCase()) ||
      h.comment?.toLowerCase().includes(search.toLowerCase()),
  )

  const handleAdd = useCallback(() => {
    if (!newIp.trim() || !newHostname.trim()) return
    const newEntry: HostEntry = {
      ip: newIp.trim(),
      hostname: newHostname.trim(),
      enabled: true,
      comment: newComment.trim() || undefined,
    }
    setHosts((prev) => [...prev, newEntry])
    setNewIp('')
    setNewHostname('')
    setNewComment('')
  }, [newIp, newHostname, newComment])

  const handleToggle = useCallback((index: number) => {
    setHosts((prev) => prev.map((h, i) => (i === index ? { ...h, enabled: !h.enabled } : h)))
  }, [])

  const handleDelete = useCallback((index: number) => {
    setHosts((prev) => prev.filter((_, i) => i !== index))
  }, [])

  const handleCopy = useCallback(() => {
    const content = hosts
      .filter((h) => h.enabled)
      .map((h) => `${h.ip}\t${h.hostname}`)
      .join('\n')
    navigator.clipboard.writeText(content)
    setCopied(true)
    setTimeout(() => setCopied(false), 1500)
  }, [hosts])

  const handleExport = useCallback(() => {
    const content = [
      '# Hosts file',
      '# Generated by Polaris Host Editor',
      '',
      ...hosts.map((h) => {
        const prefix = h.enabled ? '' : '# '
        const comment = h.comment ? ` # ${h.comment}` : ''
        return `${prefix}${h.ip}\t${h.hostname}${comment}`
      }),
    ].join('\n')
    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'hosts'
    a.click()
    URL.revokeObjectURL(url)
  }, [hosts])

  return (
    <div style={{ padding: 12, display: 'flex', flexDirection: 'column', height: '100%', gap: 8, fontFamily: 'system-ui, sans-serif' }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <h3 style={{ margin: 0, fontSize: 13, fontWeight: 600, color: '#E8E8EC' }}>Hosts 编辑</h3>
        <span style={{ fontSize: 10, color: '#71717A' }}>Plugin: {pluginId}</span>
      </div>

      {/* Search & Actions */}
      <div style={{ display: 'flex', gap: 6 }}>
        <input
          type="text"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          placeholder="搜索..."
          style={{
            flex: 1,
            padding: '6px 10px',
            borderRadius: 6,
            border: '1px solid #3F3F46',
            background: '#18181B',
            color: '#E8E8EC',
            fontSize: 12,
            outline: 'none',
          }}
        />
        <button
          onClick={handleCopy}
          style={{
            padding: '6px 10px',
            borderRadius: 6,
            border: '1px solid #3F3F46',
            background: copied ? '#22C55E' : '#27272A',
            color: copied ? '#fff' : '#A1A1AA',
            fontSize: 11,
            cursor: 'pointer',
          }}
        >
          {copied ? '已复制' : '复制'}
        </button>
        <button
          onClick={handleExport}
          style={{
            padding: '6px 10px',
            borderRadius: 6,
            border: '1px solid #3F3F46',
            background: '#27272A',
            color: '#A1A1AA',
            fontSize: 11,
            cursor: 'pointer',
          }}
        >
          导出
        </button>
      </div>

      {/* Add New Entry */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 4, padding: 8, borderRadius: 6, background: '#27272A', border: '1px solid #3F3F46' }}>
        <div style={{ fontSize: 11, color: '#71717A', marginBottom: 4 }}>添加新条目</div>
        <div style={{ display: 'flex', gap: 6 }}>
          <input
            type="text"
            value={newIp}
            onChange={(e) => setNewIp(e.target.value)}
            placeholder="IP 地址"
            style={{ flex: 1, padding: '6px 10px', borderRadius: 4, border: '1px solid #3F3F46', background: '#18181B', color: '#E8E8EC', fontSize: 11, outline: 'none' }}
          />
          <input
            type="text"
            value={newHostname}
            onChange={(e) => setNewHostname(e.target.value)}
            placeholder="主机名"
            style={{ flex: 1, padding: '6px 10px', borderRadius: 4, border: '1px solid #3F3F46', background: '#18181B', color: '#E8E8EC', fontSize: 11, outline: 'none' }}
          />
        </div>
        <div style={{ display: 'flex', gap: 6 }}>
          <input
            type="text"
            value={newComment}
            onChange={(e) => setNewComment(e.target.value)}
            placeholder="备注 (可选)"
            style={{ flex: 1, padding: '6px 10px', borderRadius: 4, border: '1px solid #3F3F46', background: '#18181B', color: '#E8E8EC', fontSize: 11, outline: 'none' }}
          />
          <button
            onClick={handleAdd}
            disabled={!newIp.trim() || !newHostname.trim()}
            style={{
              padding: '6px 12px',
              borderRadius: 4,
              border: 'none',
              background: newIp.trim() && newHostname.trim() ? '#3B82F6' : '#3F3F46',
              color: newIp.trim() && newHostname.trim() ? '#fff' : '#71717A',
              fontSize: 11,
              cursor: newIp.trim() && newHostname.trim() ? 'pointer' : 'not-allowed',
            }}
          >
            添加
          </button>
        </div>
      </div>

      {/* Hosts List */}
      <div style={{ flex: 1, overflow: 'auto', display: 'flex', flexDirection: 'column', gap: 2 }}>
        {filtered.map((h, i) => (
          <div
            key={`${h.ip}-${h.hostname}-${i}`}
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: 8,
              padding: '6px 10px',
              borderRadius: 4,
              background: h.enabled ? '#18181B' : '#18181B80',
              border: '1px solid #27272A',
              opacity: h.enabled ? 1 : 0.6,
            }}
          >
            <button
              onClick={() => handleToggle(hosts.indexOf(h))}
              style={{
                width: 16,
                height: 16,
                borderRadius: 4,
                border: '1px solid',
                borderColor: h.enabled ? '#22C55E' : '#3F3F46',
                background: h.enabled ? '#22C55E' : 'transparent',
                cursor: 'pointer',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                fontSize: 10,
                color: '#fff',
                padding: 0,
              }}
            >
              {h.enabled && '✓'}
            </button>
            <div style={{ flex: 1, minWidth: 0 }}>
              <div style={{ display: 'flex', gap: 8, fontSize: 11, fontFamily: 'monospace' }}>
                <span style={{ color: '#3B82F6' }}>{h.ip}</span>
                <span style={{ color: '#71717A' }}>→</span>
                <span style={{ color: '#E8E8EC' }}>{h.hostname}</span>
              </div>
              {h.comment && <div style={{ fontSize: 10, color: '#52525B' }}>{h.comment}</div>}
            </div>
            <button
              onClick={() => handleDelete(hosts.indexOf(h))}
              style={{
                padding: '2px 6px',
                borderRadius: 3,
                border: '1px solid #EF444440',
                background: 'transparent',
                color: '#EF4444',
                fontSize: 9,
                cursor: 'pointer',
              }}
            >
              删除
            </button>
          </div>
        ))}
      </div>

      {/* Info */}
      <div style={{ padding: '6px 10px', borderRadius: 6, background: '#27272A', fontSize: 10, color: '#71717A' }}>
        禁用的条目会以注释形式保留在导出文件中。
      </div>
    </div>
  )
}
