/**
 * cap.capability — cap 自身管理(元 cap)
 *
 * 动作: list/get/unregister/schema/stats/scaffold/read/files/write
 * AI 可查询所有 cap 的 schema, 也可卸载 cap (动态架构),
 * 或用 scaffold 生成符合契约的插件骨架.
 *
 * scaffold / read / files / write 共同构成 AI 自我演化的闭环, 是插件文件的
 * 唯一入口:
 *   scaffold { name, capId, content? }  → 生成并校验, content 可整体替换 index.ts
 *   read     { file: "index.ts" }        → 读回自己刚写的文件
 *   write    { file: "index.ts", content }
 *   files    { }                         → 列出已生成但未安装的插件目录
 * 之后 AI 只需 cap.plugin install 即可热生效, 全程不碰 cap.fs.
 *
 * 为什么必须有 read/write, 而不是让 AI 用 cap.fs: 两个能力根不同.
 * scaffold 写的是加载器扫描的 pluginsRoot (项目 plugins/), 而 cap.fs 沙箱根
 * 是 dataRoot (%APPDATA%/Polaris-sky). 同名相对路径 "plugins/foo" 在两者下
 * 指向不同位置 — 实测 AI 会拿 scaffold 生成后立刻用 cap.fs 去改, 结果写进
 * dataRoot 而脚手架留在项目里, manifest 读不到, 于是空转十几轮. 收拢到一个
 * cap 后路径只有一个真相源.
 *
 * 之所以不用 ctx.dispatch('cap.fs') 实现: 模板用 '../../src/contracts.ts' 相对
 * 导入, 只有落在项目 plugins/ 内该路径才成立. cap.fs 沙箱限 dataRoot 是有意
 * 为之, 不应为生成插件而放宽.
 */

import type { Capability, CallContext, Value } from '../contracts.ts';
import type { Router } from '../server/router.ts';
import { existsSync, mkdirSync, writeFileSync, readFileSync, readdirSync, statSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';

export interface CapabilityCapParams {
  action: 'list' | 'get' | 'unregister' | 'schema' | 'stats' | 'scaffold' | 'read' | 'files' | 'write';
  cap?: string;
  // scaffold 用
  name?: string;
  id?: string;
  capId?: string;
  directory?: string;
  overwrite?: boolean;
  verify?: boolean;
  content?: string;
  file?: string;
}

export interface CapabilityCapOptions {
  /** 插件落盘根目录. 不传则 scaffold 返回模板内容但不写盘 (退化为纯生成器). */
  pluginsRoot?: string;
}

/** 目录名白名单: 必须与 pluginsRoot 内目录结构约定一致 (一个插件一个目录). */
function slugDir(name: string): string | null {
  const s = String(name || '').trim();
  if (!s || s.length > 64) return null;
  return /^[a-z][a-z0-9-]*$/.test(s) ? s : null;
}

/**
 * 按生成位置到 sky/ 根的上溯级数构造导入前缀.
 * plugins/<name>/index.ts 需上溯 2 级, 故传入 2.
 */
function importPrefix(levelsUp: number): string {
  return '../'.repeat(levelsUp) + 'src/';
}

function buildManifest(id: string, name: string, capId: string): string {
  return [
    '{',
    `  "id": "${id}",`,
    `  "name": "${name}",`,
    '  "version": "0.1.0",',
    '  "description": "Generated by cap.capability scaffold. Edit freely.",',
    `  "caps": ["${capId}"]`,
    '}',
    '',
  ].join('\n');
}

function buildIndex(capId: string, prefix: string): string {
  return [
    '/**',
    ` * ${capId} — 由 cap.capability scaffold 生成.`,
    ' *',
    ' * 契约铁律 (违反任意一条都装不上或调不通):',
    ' *   1. 必须 default export 一个 setup(router) 函数, 在函数内 router.register(cap).',
    ' *   2. cap 必须实现 Capability 接口 — invoke(params, ctx) 返回 Promise<Value>.',
    ' *      不要用 actions 字典 + 自定义分发, Router 只认 invoke.',
    ' *   3. 调其他 cap 走 ctx.dispatch, 不要直接 import 别的 cap 模块 —',
    ' *      直接 import 会绕过 permission/audit 拦截器链, 等于开了后门.',
    ' *   4. 返回值包一层 { ok: true, ... } 才与全项目约定一致.',
    ' */',
    '',
    `import type { Capability, CallContext, Value } from '${prefix}contracts.ts';`,
    `import type { Router } from '${prefix}server/router.ts';`,
    '',
    'type Params = {',
    '  action: string;',
    '  color?: string;',
    '  to?: "hex" | "rgb";',
    '};',
    '',
    'const cap: Capability = {',
    `  id: '${capId}',`,
    "  description: 'Convert or generate colors. Actions: random/convert.',",
    '  inputSchema: {',
    '    type: "object",',
    '    properties: {',
    '      action: { type: "string", enum: ["random", "convert"] },',
    '      color: { type: "string", description: "#ff0000 或 rgb(255,0,0)" },',
    '      to: { type: "string", enum: ["hex", "rgb"] },',
    '    },',
    "    required: ['action'],",
    '  },',
    '  async invoke(params: Value, _ctx: CallContext) {',
    '    const p = (params ?? {}) as Params;',
    '',
    '    if (p.action === "random") {',
    "      const n = Math.floor(Math.random() * 0xffffff);",
    '      return {',
    '        ok: true,',
    "        hex: '#' + n.toString(16).padStart(6, '0'),",
    "        rgb: `rgb(${n >> 16},${(n >> 8) & 0xff},${n & 0xff})`,",
    '      };',
    '    }',
    '',
    '    if (p.action === "convert" && p.color) {',
    '      if (p.color.startsWith("#")) {',
    '        const r = parseInt(p.color.slice(1, 3), 16);',
    '        const g = parseInt(p.color.slice(3, 5), 16);',
    '        const b = parseInt(p.color.slice(5, 7), 16);',
    '        return { ok: true, input: p.color, hex: p.color, rgb: `rgb(${r},${g},${b})`, r, g, b };',
    '      }',
    '      const m = p.color.match(/rgb\\((\\d+),\\s*(\\d+),\\s*(\\d+)\\)/);',
    '      if (m) {',
    '        const [r, g, b] = [m[1], m[2], m[3]].map(Number);',
    "        return { ok: true, input: p.color, rgb: p.color, hex: '#' + [r, g, b]",
    "          .map(v => v.toString(16).padStart(2, '0')).join(''), r, g, b };",
    '      }',
    "      return { ok: false, error: 'invalid color format' };",
    '    }',
    '',
    "    return { ok: false, error: 'unsupported action: ' + p.action };",
    '  },',
    '};',
    '',
    'export default function setup(router: Router) {',
    '  router.register(cap);',
    '}',
    '',
    'export async function teardown(router: Router) {',
    `  router.unregister('${capId}');`,
    '}',
    '',
  ].join('\n');
}

export function createCapabilityCap(router: Router, options: CapabilityCapOptions = {}): Capability {
  const pluginsRoot = options.pluginsRoot;
  return {
    id: 'cap.capability',
    description:
      'Capability manager. Actions: list/get/unregister/schema/stats/scaffold/read/files/write. AI can inspect all caps and manage plugin scaffolds (generate, edit, read back) end to end.',
    inputSchema: {
      type: 'object',
      properties: {
        action: {
          type: 'string',
          enum: ['list', 'get', 'unregister', 'schema', 'stats', 'scaffold', 'read', 'files', 'write'],
        },
        cap: { type: 'string', description: 'Capability id (get/schema/unregister)' },
        // scaffold 用
        name: { type: 'string', description: 'scaffold: plugin dir name, e.g. "color-picker"' },
        id: { type: 'string', description: 'scaffold: plugin id, e.g. "plugin.color-picker"' },
        capId: { type: 'string', description: 'scaffold: capability id the plugin exposes, e.g. "cap.color"' },
        directory: {
          type: 'string',
          description:
            'scaffold: 必须等于 "./<name>" (如 "./mood"). 只有一层子目录才能成立 — ' +
            '更深的路径会让模板的 "../../src/contracts.ts" 相对导入失效.',
        },
        content: {
          type: 'string',
          description: 'scaffold/write: full file content. For scaffold, overrides the generated index.ts.',
        },
        overwrite: { type: 'boolean', description: 'scaffold: overwrite existing files (default false)' },
        verify: { type: 'boolean', description: 'scaffold: import the generated file to check syntax (default true)' },
        // read / files / write 用
        file: { type: 'string', description: 'read/files/write: file name inside the plugin dir (index.ts | manifest.json)' },
      },
      required: ['action'],
    },
    async invoke(params: Value, _ctx: CallContext) {
      const p = params as CapabilityCapParams;

      switch (p.action) {
        case 'list':
          return { ok: true, caps: router.list() };
        case 'get': {
          if (!p.cap) throw new Error('cap required for get');
          const found = router.list().find(c => c.id === p.cap);
          if (!found) return { ok: false, notFound: true };
          return { ok: true, capability: found };
        }
        case 'schema': {
          if (!p.cap) throw new Error('cap required for schema');
          const found = router.list().find(c => c.id === p.cap);
          if (!found) return { ok: false, notFound: true };
          return { ok: true, id: found.id, inputSchema: found.inputSchema, description: found.description, streaming: found.streaming };
        }
        case 'unregister': {
          if (!p.cap) throw new Error('cap required for unregister');
          router.unregister(p.cap);
          return { ok: true, unregistered: p.cap };
        }
        case 'stats': {
          const all = router.list();
          return {
            ok: true,
            total: all.length,
            streaming: all.filter(c => c.streaming).length,
            ids: all.map(c => c.id),
          };
        }
        case 'scaffold':
          return await scaffoldPlugin(p);
        case 'read':
          return readPluginFile(p);
        case 'files':
          return listPluginFiles();
        case 'write':
          return await writePluginFile(p);
        default:
          throw new Error(`unknown action: ${(p as { action: string }).action}`);
      }

      // 抽成函数: 参数校验 + 写盘 + 语法校验, 便于单独测试与复用.
      async function scaffoldPlugin(
        p: CapabilityCapParams,
      ): Promise<Value> {
        const dirName = p.name ? slugDir(p.name) : null;
        if (!dirName) {
          return {
            ok: false,
            error: 'scaffold: name must match /^[a-z][a-z0-9-]*$/ (lowercase, starts with letter)',
          };
        }
        const pluginId = p.id ?? `plugin.${dirName.replace(/-/g, '.')}`;
        const capId = p.capId ?? `cap.${dirName.replace(/-/g, '')}`;

        const manifest = buildManifest(pluginId, dirName, capId);
        // plugins/<name>/index.ts → 上溯 2 级到 sky/ 再进 src/
        // content 可整体替换 index.ts, 让 AI 一步到位写出实现 (无需 scaffold 后再 write)
        const index = p.content ?? buildIndex(capId, importPrefix(2));

        const result: Record<string, unknown> = {
          ok: true,
          generated: { 'manifest.json': manifest, 'index.ts': index },
        };

        if (!pluginsRoot) {
          result.written = false;
          result.reason = 'pluginsRoot not configured — content returned only';
          return result;
        }

        // 目标目录: 默认 pluginsRoot/<name>, 允许显式指定子目录 (嵌套时导入前缀会失配, 故禁止)
        const relDir = (p.directory && p.directory.trim()) || `./${dirName}`;
        if (relDir !== `./${dirName}`) {
          return { ok: false, error: 'scaffold: directory must be "./<name>" (nested paths break the import prefix)' };
        }
        const dir = join(pluginsRoot, relDir);
        const manifestPath = join(dir, 'manifest.json');
        const indexPath = join(dir, 'index.ts');

        if (existsSync(manifestPath) && !p.overwrite) {
          return {
            ok: false,
            error: `directory already exists: ${dir} (pass overwrite:true to regenerate)`,
          };
        }
        mkdirSync(dir, { recursive: true });
        writeFileSync(manifestPath, manifest, 'utf8');
        writeFileSync(indexPath, index, 'utf8');
        result.written = true;
        result.path = dir;
        result.files = { manifest: manifestPath, index: indexPath };

        // 语法校验: 真 import 一次, 确认 setup 是函数. 失败则回滚, 不留半成品.
        if (p.verify !== false) {
          try {
            const mod = await import(pathToFileURL(indexPath).href);
            const isSetup = typeof mod.default === 'function';
            result.verified = isSetup;
            if (!isSetup) {
              result.verifyError = 'generated index.ts has no default export function';
            }
          } catch (err) {
            const msg = err instanceof Error ? err.message : String(err);
            result.verified = false;
            result.verifyError = msg;
            // 回滚: 生成即校验, 失败不留半成品目录
            rmSync(dir, { recursive: true, force: true });
            result.rolledBack = true;
            return { ok: false, error: `scaffold failed syntax check: ${msg}`, path: dir };
          }
        }

        result.nextSteps = [
          'edit: cap.capability { action: "write", name: "' + dirName + '", file: "index.ts", content: "...", verify: true }',
          'check: cap.capability { action: "read", name: "' + dirName + '", file: "index.ts" }',
          'install: cap.plugin { action: "install", path: "' + relDir + '" }',
          'call: ' + capId + ' { action: "..." }',
        ];
        return result;
      }

      // 插件文件读取. 与 scaffold 同一真相源 (pluginsRoot), 不经 cap.fs 沙箱.
      function readPluginFile(p: CapabilityCapParams): Value {
        if (!pluginsRoot) return { ok: false, error: 'pluginsRoot not configured' };
        const dirName = p.name ? slugDir(p.name) : null;
        if (!dirName) return { ok: false, error: 'read: name required, must match /^[a-z][a-z0-9-]*$/' };
        const file = validatePluginFile(p.file ?? 'index.ts');
        if (!file) return { ok: false, error: 'read: file must be "index.ts" or "manifest.json"' };
        const path = join(pluginsRoot, dirName, file);
        if (!existsSync(path)) return { ok: false, notFound: true, path };
        const content = readFileSync(path, 'utf8');
        return { ok: true, name: dirName, file, path, content, bytes: content.length };
      }

      // 列出 pluginsRoot 下所有插件目录及其文件 (AI 判断哪些已生成但未安装).
      function listPluginFiles(): Value {
        if (!pluginsRoot || !existsSync(pluginsRoot)) return { ok: true, plugins: [] };
        const out: Array<Record<string, unknown>> = [];
        for (const entry of readdirSync(pluginsRoot)) {
          const dir = join(pluginsRoot, entry);
          if (!statSync(dir).isDirectory()) continue;
          const manifestPath = join(dir, 'manifest.json');
          const pluginId = existsSync(manifestPath)
            ? JSON.parse(readFileSync(manifestPath, 'utf8')).id
            : null;
          out.push({
            name: entry,
            path: pluginId ? `./${entry}` : null,
            pluginId,
            files: readdirSync(dir),
            installable: !!pluginId && !!existsSync(join(dir, 'index.ts')),
          });
        }
        return { ok: true, plugins: out };
      }

      // 写入插件文件并可选语法校验. 用新 URL 绕过 ESM 模块缓存.
      async function writePluginFile(p: CapabilityCapParams): Promise<Value> {
        if (!pluginsRoot) return { ok: false, error: 'pluginsRoot not configured' };
        const dirName = p.name ? slugDir(p.name) : null;
        if (!dirName) return { ok: false, error: 'write: name required, must match /^[a-z][a-z0-9-]*$/' };
        const file = validatePluginFile(p.file ?? 'index.ts');
        if (!file) return { ok: false, error: 'write: file must be "index.ts" or "manifest.json"' };
        if (typeof p.content !== 'string' || !p.content.trim()) {
          return { ok: false, error: 'write: content required (non-empty string)' };
        }
        const dir = join(pluginsRoot, dirName);
        const path = join(dir, file);
        mkdirSync(dir, { recursive: true });
        writeFileSync(path, p.content, 'utf8');
        const result: Record<string, unknown> = { ok: true, name: dirName, file, path, bytes: p.content.length };

        // 写 index.ts 但不带 manifest.json → 自动补齐. 否则纯 write 路径创建的
        // 目录无法 install (报 manifest.json not found), AI 会卡在一个装不上的死胡同.
        // 只写 index.ts 时补 — 显式写 manifest.json 则尊重 AI 自己的内容.
        if (file === 'index.ts') {
          const manifestPath = join(dir, 'manifest.json');
          if (!existsSync(manifestPath)) {
            const pluginId = `plugin.${dirName.replace(/-/g, '.')}`;
            const defaultCapId = `cap.${dirName.replace(/-/g, '')}`;
            writeFileSync(manifestPath, buildManifest(pluginId, dirName, defaultCapId), 'utf8');
            result.manifestCreated = manifestPath;
            result.capIdGuess = defaultCapId;
            result.note =
              'manifest.json auto-created. If your index.ts registers a different cap id, ' +
              'update manifest.json "caps" via write.';
          }
        }

        if (file === 'index.ts' && p.verify !== false) {
          // tsx 的 import 缓存按 URL 命中, 每次改完必须换新 query 才能重新编译
          const url = pathToFileURL(path).href + '?v=' + Date.now();
          try {
            const mod = await import(url);
            result.verified = true;
            if (typeof mod.default !== 'function') {
              result.verified = false;
              result.verifyError = 'index.ts must default-export a setup function';
            }
            if (mod.default && typeof mod.teardown !== 'function') {
              result.verifyWarning = 'teardown not exported (optional)';
            }
          } catch (err) {
            const msg = err instanceof Error ? err.message : String(err);
            // 注意: 写成功了 (内容已在盘上), 只是解析失败. 如实报告 ok:true,
            // verified:false — 若返回 ok:false, AI 会以为写入失败, 用同样内容重试
            // 并再次失败, 形成死循环. 正确的下一步是 read 回来看, 改, 再 write.
            // install 一份坏代码也不会静默成功: installPlugin 的 import 会抛错并被捕获.
            result.verified = false;
            result.verifyError = msg;
            result.actionNeeded =
              'file was written but does not parse — read it back, fix, and write again. ' +
              'do NOT install until verified=true.';
          }
        }
        result.installHint = `cap.plugin { action: "install", path: "./${dirName}" }`;
        return result;
      }
    },
  };
}

/** 插件目录内允许读写的文件白名单 (与 plugin-loader 的约定一致). */
const PLUGIN_FILES = new Set(['index.ts', 'manifest.json']);

function validatePluginFile(file: string): string | null {
  const s = String(file || '').trim();
  return PLUGIN_FILES.has(s) ? s : null;
}
