/*! MCP 桥接共享模块
 *
 * 为 CLI 类 AI 引擎提供 MCP 桥接能力，将 Polaris 解析的 MCP server 列表
 * 桥接为子进程可调用的 LLM 工具。
 *
 * 目前支持 Pi Extension 风格（Pi / OMP 兼容）：
 * 写一个 JS Extension 文件 + config.json，子进程通过 `--extension <dir>` 加载，
 * Extension 内部 spawn stdio MCP server 子进程，通过 `pi.registerTool()`
 * 把每个 MCP 工具注册为 LLM 工具。
 *
 * 该模块从 PiEngine 提取，供 PluginEngineRunner 等通用引擎适配器复用，
 * 避免 OMP 等插件引擎缺失 MCP 桥接（与 Pi 引擎能力不对齐）。
 */

use std::fs;
use std::path::Path;

use crate::services::mcp_config_service::ResolvedExternalMcpServer;

/// Polaris MCP 桥接 Extension 的 JavaScript 源码。
///
/// 这是一个 Pi Extension（TypeScript/JavaScript 模块），通过 Pi 的 Extension API
/// 加载 stdio MCP server 子进程，把 MCP 工具注册为 Pi 可调用的工具。
///
/// 工作机制：
/// 1. 读取同目录下的 config.json 获取 MCP server 列表
/// 2. 对每个 MCP server spawn 子进程
/// 3. JSON-RPC initialize + tools/list 发现工具
/// 4. 通过 pi.registerTool() 注册每个工具给 LLM
/// 5. 执行工具时转发 MCP tools/call 请求
///
/// 兼容性：OMP（Oh My Pi）与 Pi 共用同一 Extension API，实测 `pi.registerTool()`
/// + TypeBox 均可用，因此本桥接对两者通用。
pub const EXTENSION_SOURCE: &str = r##"// Polaris MCP Bridge Extension for Pi/OMP
// Auto-generated by Polaris. Do not edit manually.
import { spawn } from "node:child_process";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { Type } from "@sinclair/typebox";

function toTypeBox(schema) {
  if (!schema || schema === true) return Type.Any();
  if (schema === false) return Type.Never();
  switch (schema.type) {
    case "string":
      return schema.enum ? Type.Union(schema.enum.map((e) => Type.Literal(e))) : Type.String();
    case "number":
      return Type.Number();
    case "integer":
      return Type.Integer();
    case "boolean":
      return Type.Boolean();
    case "array":
      return Type.Array(schema.items ? toTypeBox(schema.items) : Type.Any());
    case "object": {
      if (!schema.properties) return Type.Record(Type.String(), Type.Any());
      const required = schema.required;
      const hasRequired = Array.isArray(required) && required.length > 0;
      const requiredSet = new Set(hasRequired ? required : []);
      const props = {};
      for (const [key, val] of Object.entries(schema.properties)) {
        let propSchema = toTypeBox(val);
        if (!hasRequired || !requiredSet.has(key)) {
          propSchema = Type.Optional(propSchema);
        }
        props[key] = propSchema;
      }
      return Type.Object(props, { additionalProperties: schema.additionalProperties !== false });
    }
    default:
      return Type.Any();
  }
}

function mcpRequest(process, request) {
  return new Promise((resolve, reject) => {
    const requestId = request.id || 1;
    const requestStr = JSON.stringify({ ...request, id: requestId, jsonrpc: "2.0" }) + "\n";
    let buffer = "";
    let done = false;

    const onData = (data) => {
      if (done) return;
      buffer += data.toString();
      const lines = buffer.split("\n");
      buffer = lines.pop() || "";
      for (const line of lines) {
        if (!line.trim()) continue;
        try {
          const response = JSON.parse(line);
          if (response.id === requestId) {
            done = true;
            process.stdout.removeListener("data", onData);
            if (response.error) reject(new Error(response.error.message));
            else resolve(response);
          }
        } catch {}
      }
    };

    process.stdout.on("data", onData);
    process.stdin.write(requestStr);

    setTimeout(() => {
      if (!done) {
        done = true;
        process.stdout.removeListener("data", onData);
        reject(new Error("MCP request timeout"));
      }
    }, 300000);
  });
}

export default async function (pi) {
  const configPath = fileURLToPath(new URL("./config.json", import.meta.url));
  let config;
  try {
    config = JSON.parse(readFileSync(configPath, "utf-8"));
  } catch (e) {
    console.error("[polaris-mcp] Failed to load config.json:", e.message);
    return;
  }

  const servers = config.mcpServers || [];
  if (!servers.length) {
    console.log("[polaris-mcp] No MCP servers configured");
    return;
  }

  await Promise.all(servers.map(async (srv) => {
    console.log("[polaris-mcp] Connecting to server:", srv.serverName);
    let proc;
    try {
      proc = spawn(srv.command, srv.args, { stdio: ["pipe", "pipe", "pipe"] });
      proc.on("error", (err) => console.error("[polaris-mcp] Spawn error:", srv.serverName, err.message));
      proc.stderr.on("data", (d) => console.error("[polaris-mcp] stderr:", srv.serverName, d.toString().trim()));
    } catch (e) {
      console.error("[polaris-mcp] Failed to spawn:", srv.serverName, e.message);
      return;
    }

    let initResult;
    try {
      initResult = await mcpRequest(proc, {
        method: "initialize",
        params: { protocolVersion: "2024-11-05", capabilities: {}, clientInfo: { name: "polaris-mcp-bridge", version: "1.0.0" } },
      });
    } catch (e) {
      console.error("[polaris-mcp] Initialize failed:", srv.serverName, e.message);
      return;
    }

    let toolsResult;
    try {
      toolsResult = await mcpRequest(proc, { method: "tools/list", params: {} });
    } catch (e) {
      console.error("[polaris-mcp] tools/list failed:", srv.serverName, e.message);
      return;
    }

    const tools = toolsResult.result?.tools || [];
    for (const tool of tools) {
      // 注册工具时使用纯 mcp__{server}__{tool} 名，不添加 xd:// 前缀。
      // OMP 的 write 工具设备解析存在 xd:// 前缀剥离不一致问题：
      // 注册的设备带 xd:// 前缀，但 write 解析路径时剥离前缀后找不到设备。
      // 去掉前缀后 OMP 将其视为普通工具，LLM 直接调用工具名，绕过 write 层。
      const toolName = `mcp__${srv.serverName}__${tool.name}`;
      pi.registerTool({
        name: toolName,
        label: tool.name,
        description: tool.description || "",
        parameters: toTypeBox(tool.inputSchema),
        async execute(toolCallId, params, signal, onUpdate, ctx) {
          try {
            const result = await mcpRequest(proc, {
              method: "tools/call",
              params: { name: tool.name, arguments: params },
            });
            const content = result.result?.content || [];
            const text = content.map((c) => c.text || JSON.stringify(c)).join("\n");
            // 透传 structuredContent：以 ```json fence 块形式追加到文本末尾，
            // 前端 parseCardData 的 fenced 提取逻辑能识别并渲染卡片。
            const sc = result.result?.structuredContent;
            const output = sc ? text + "\n```json\n" + JSON.stringify(sc) + "\n```" : text;
            return { content: [{ type: "text", text: output }] };
          } catch (e) {
            return { content: [{ type: "text", text: "Error: " + e.message }], isError: true };
          }
        },
      });
      console.log("[polaris-mcp] Registered tool:", toolName, "from", srv.serverName);
    }
  }));
}
"##;

/// 写入 Extension 桥接文件（index.js + config.json）。
///
/// 把 MCP server 列表写入 `<bridge_dir>/`，供 Extension 在 CLI 启动时加载并桥接为 LLM 工具。
///
/// - `bridge_dir`：Extension 目录（如 `~/.pi/agent/extensions/polaris-mcp-bridge/`）。
/// - `servers`：Polaris 解析的 MCP server 列表。
pub fn write_extension_bridge(
    bridge_dir: &Path,
    servers: &[ResolvedExternalMcpServer],
) -> Result<(), crate::error::AppError> {
    fs::create_dir_all(bridge_dir)?;

    // 写入 index.js（Extension 源码）
    let js_path = bridge_dir.join("index.js");
    fs::write(&js_path, EXTENSION_SOURCE)?;

    // 写入 config.json（MCP server 列表）
    let config_path = bridge_dir.join("config.json");
    let config_json = serde_json::json!({
        "mcpServers": servers.iter().map(|srv| serde_json::json!({
            "serverName": srv.server_name,
            "command": srv.command,
            "args": srv.args,
        })).collect::<Vec<_>>()
    });
    let content = serde_json::to_string_pretty(&config_json)?;
    fs::write(&config_path, content)?;

    tracing::info!(
        "[McpBridge] 已写入 Extension 桥接: {} 个 MCP server 到 {}",
        servers.len(),
        bridge_dir.display()
    );
    Ok(())
}